
name: handwriting_rnn
channels:
  - menpo
  - glemaitre
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - pandas
  - h5py
  - ipywidgets
  - svgwrite
  - tensorflow=1.4.0
  - scipy
  - sklearn
